#!/usr/bin/env bash
set -e

TARGET="$HOME/.local/go-tools/bin"
mkdir -p "$TARGET"




echo "Generating config_local.go with repo root..."
GO_TOOLS_ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_LOCAL="$(dirname "$0")/cmd/go-tools/config_local.go"
cat > "$CONFIG_LOCAL" <<EOF
// This file is generated by setup.sh and should not be committed.
// +build !prod

package main

const hardcodedRepoRoot = "$GO_TOOLS_ROOT_DIR"
EOF

export GO_TOOLS_ROOT_DIR="$GO_TOOLS_ROOT_DIR"

echo "Building go-tools manager..."
go build -o "$TARGET/go-tools" ./cmd/go-tools

echo "(Astuce: pour une solution flexible, exportez GO_TOOLS_ROOT_DIR avant d'utiliser go-tools)"

echo ""
echo "Installed go-tools in $TARGET"
echo ""

if [[ ":$PATH:" != *":$TARGET:"* ]]; then
  echo "Add this to your ~/.zshrc or ~/.bashrc:"
  echo ""
  echo "export PATH=\"$HOME/.local/go-tools/bin:\$PATH\""
  echo ""
else
  echo "PATH already configured."
fi