package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"github.com/spf13/cobra"
	"go-tools/pkg/lib"
)

func newInstallCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install go-tools binaries",
		RunE: runInstall,
	}
	return cmd
}

func runInstall(cmd *cobra.Command, args []string) error {
	repoRoot := getRepoRoot()
	targetDir := filepath.Join(os.Getenv("HOME"), ".local", "go-tools", "bin")
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		return err
	}
	cmdDir := filepath.Join(repoRoot, "cmd")
	entries, err := os.ReadDir(cmdDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if name == "go-tools" {
			continue
		}
		fmt.Println("→ Building", name)
		build := exec.Command(
			"go", "build",
			"-o", filepath.Join(targetDir, name),
			filepath.Join(cmdDir, name),
		)
		build.Stdout = os.Stdout
		build.Stderr = os.Stderr
		if err := build.Run(); err != nil {
			return err
		}
	}
	fmt.Println("✅ Installed to", targetDir)
	return nil
}

// hardcodedRepoRoot is defined in config_local.go, which is ignored by git and generated by setup.sh
func getRepoRoot() string {
	envRepoRoot := os.Getenv("GO_TOOLS_ROOT_DIR")
	if envRepoRoot != "" {
		return envRepoRoot
	}
	if hardcodedRepoRoot != "" {
		return hardcodedRepoRoot
	}
	lib.Exit(fmt.Errorf("GO_TOOLS_ROOT_DIR not set and hardcodedRepoRoot is empty"))
	return "" // unreachable
}