package main

import (
	"bytes"
	"fmt"
	"go-tools/pkg/lib"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

func newInstallCommand() *cobra.Command {
	var allFlag bool
	var noCompletions bool
	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install go-tools binaries",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInstall(cmd, args, allFlag, noCompletions)
		},
	}
	cmd.Flags().BoolVar(&allFlag, "all", false, "Install all binaries, including go-tools itself")
	cmd.Flags().BoolVar(&noCompletions, "no-completions", false, "Skip generating shell completions after install")
	return cmd
}

func runInstall(_ *cobra.Command, _ []string, all bool, noCompletions bool) error {
	repoRoot := getRepoRoot()
	goModPath := filepath.Join(repoRoot, "go.mod")
	if st, err := os.Stat(goModPath); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf(
				"invalid GO_TOOLS_ROOT_DIR (%q): no go.mod found at %q\n\n"+
					"Fix: set GO_TOOLS_ROOT_DIR to the go-tools repository root (the folder that contains go.mod).\n"+
					"Tip: if you use this repo's setup, run setup.sh to generate cmd/go-tools/config_local.go",
				repoRoot,
				goModPath,
			)
		}
		return fmt.Errorf("failed to stat %q: %w", goModPath, err)
	} else if st.IsDir() {
		return fmt.Errorf("invalid module root: %q is a directory", goModPath)
	}
	targetDir := goToolsBinDir()
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		return err
	}
	cmdDir := filepath.Join(repoRoot, "cmd")
	entries, err := os.ReadDir(cmdDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if !all && name == "go-tools" {
			continue
		}
		fmt.Println("→ Installing", name)
		install := exec.Command(
			"go", "install",
			"./cmd/"+name,
		)
		// Run from module root so the go tool can discover go.mod.
		install.Dir = repoRoot
		// Install into our target directory (rather than GOPATH/bin).
		install.Env = append(os.Environ(), "GOBIN="+targetDir)
		install.Stdout = os.Stdout
		// Capture stderr: the go compiler emits \r-based progress lines that
		// corrupt the terminal display. Show it only when the build fails.
		var stderrBuf bytes.Buffer
		install.Stderr = &stderrBuf
		if err := install.Run(); err != nil {
			os.Stderr.Write(stderrBuf.Bytes())
			repro := "cd " + repoRoot + " && GOBIN=" + targetDir + " " + strings.Join(install.Args, " ")
			return fmt.Errorf("install failed for %q\ncommand: %s\nerror: %w", name, repro, err)
		}
	}
	fmt.Println("✅ Installed to", targetDir)

	if noCompletions {
		return nil
	}

	fmt.Println()
	shell := detectShell()
	if shell == nil {
		fmt.Println("⚠️  Could not detect shell from $SHELL — skipping completion generation.")
		fmt.Println("   Run 'go-tools completions install' manually.")
		return nil
	}

	fmt.Printf("→ Generating completions for %s\n", shell.name)
	res, err := installCompletionsForShell(*shell)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: completion generation failed: %v\n", err)
		return nil
	}
	printCompletionResult(res)

	configured, _ := isShellConfigured(*shell)
	if !configured {
		fmt.Printf("\n⚠️  Shell not configured to source completions.\n")
		fmt.Printf("   Run: go-tools completions setup\n")
	}
	return nil
}

// hardcodedRepoRoot is defined in config_local.go, which is ignored by git and generated by setup.sh
func getRepoRoot() string {
	envRepoRoot := os.Getenv("GO_TOOLS_ROOT_DIR")
	if envRepoRoot != "" {
		return envRepoRoot
	}
	if hardcodedRepoRoot != "" {
		return hardcodedRepoRoot
	}
	lib.Exit(fmt.Errorf("GO_TOOLS_ROOT_DIR not set and hardcodedRepoRoot is empty"))
	return "" // unreachable
}
