package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"go-tools/pkg/lib"
)

func main() {

	// Handle CLI options
	if len(os.Args) > 1 {
		arg := os.Args[1]
		switch arg {
		case "-h", "--help":
			fmt.Println("Usage: go-tools [--clean] [-h|--help]")
			fmt.Println("  --clean     : supprime les binaires générés dans $HOME/.local/go-tools/bin")
			fmt.Println("  -h, --help  : affiche cette aide")
			os.Exit(0)
		case "--clean":
			cleanBinaries()
			os.Exit(0)
		}
	}


	repoRoot := getRepoRoot()
	targetDir := filepath.Join(os.Getenv("HOME"), ".local", "go-tools", "bin")
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		lib.Exit(err)
	}
	cmdDir := filepath.Join(repoRoot, "cmd")
	entries, err := os.ReadDir(cmdDir)
	if err != nil {
		lib.Exit(err)
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if name == "go-tools" {
			continue
		}
		fmt.Println("→ Building", name)
		build := exec.Command(
			"go", "build",
			"-o", filepath.Join(targetDir, name),
			filepath.Join(cmdDir, name),
		)
		build.Stdout = os.Stdout
		build.Stderr = os.Stderr
		if err := build.Run(); err != nil {
			lib.Exit(err)
		}
	}
	fmt.Println("✅ Installed to", targetDir)
}


// hardcodedRepoRoot is defined in config_local.go, which is ignored by git and generated by setup.sh
func getRepoRoot() string {
	envRepoRoot := os.Getenv("GO_TOOLS_ROOT_DIR")
	if envRepoRoot != "" {
		return envRepoRoot
	}
	if hardcodedRepoRoot != "" {
		return hardcodedRepoRoot
	}
	lib.Exit(fmt.Errorf("GO_TOOLS_ROOT_DIR not set and hardcodedRepoRoot is empty"))
	return "" // unreachable
}

// Remove all generated binaries in the bin directory
func cleanBinaries() {
	targetDir := filepath.Join(os.Getenv("HOME"), ".local", "go-tools", "bin")
	fmt.Println("Suppression de tous les binaires dans", targetDir)
	entries, err := os.ReadDir(targetDir)
	if err != nil {
		lib.Exit(err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		path := filepath.Join(targetDir, e.Name())
		if err := os.Remove(path); err != nil {
			fmt.Fprintf(os.Stderr, "Erreur suppression %s: %v\n", path, err)
		} else {
			fmt.Println("Supprimé:", path)
		}
	}
	fmt.Println("Nettoyage terminé.")
}
